DECK = [
    {"number": 1, "suit": "clubs", "name": "Ancho de Basto", "rank": 2, "position": 0},
    {"number": 2, "suit": "clubs", "name": "2 de Basto", "rank": 6, "position": 1},
    {"number": 3, "suit": "clubs", "name": "3 de Basto", "rank": 5, "position": 2},
    {"number": 4, "suit": "clubs", "name": "4 de Basto", "rank": 14, "position": 3},
    {"number": 5, "suit": "clubs", "name": "5 de Basto", "rank": 13, "position": 4},
    {"number": 6, "suit": "clubs", "name": "6 de Basto", "rank": 12, "position": 5},
    {"number": 7, "suit": "clubs", "name": "7 de Basto", "rank": 11, "position": 6},
    {"number": 10, "suit": "clubs", "name": "10 de Basto", "rank": 10, "position": 9},
    {"number": 11, "suit": "clubs", "name": "11 de Basto", "rank": 9, "position": 10},
    {"number": 12, "suit": "clubs", "name": "12 de Basto", "rank": 8, "position": 11},
    {"number": 1, "suit": "coins", "name": "1 de Oro", "rank": 7, "position": 0},
    {"number": 2, "suit": "coins", "name": "2 de Oro", "rank": 6, "position": 1},
    {"number": 3, "suit": "coins", "name": "3 de Oro", "rank": 5, "position": 2},
    {"number": 4, "suit": "coins", "name": "4 de Oro", "rank": 14, "position": 3},
    {"number": 5, "suit": "coins", "name": "5 de Oro", "rank": 13, "position": 4},
    {"number": 6, "suit": "coins", "name": "6 de Oro", "rank": 12, "position": 5},
    {"number": 7, "suit": "coins", "name": "7 de Oro", "rank": 4, "position": 6},
    {"number": 10, "suit": "coins", "name": "10 de Oro", "rank": 10, "position": 9},
    {"number": 11, "suit": "coins", "name": "11 de Oro", "rank": 9, "position": 10},
    {"number": 12, "suit": "coins", "name": "12 de Oro", "rank": 8, "position": 11},
    {"number": 1, "suit": "cups", "name": "1 de Copa", "rank": 7, "position": 0},
    {"number": 2, "suit": "cups", "name": "2 de Copa", "rank": 6, "position": 1},
    {"number": 3, "suit": "cups", "name": "3 de Copa", "rank": 5, "position": 2},
    {"number": 4, "suit": "cups", "name": "4 de Copa", "rank": 14, "position": 3},
    {"number": 5, "suit": "cups", "name": "5 de Copa", "rank": 13, "position": 4},
    {"number": 6, "suit": "cups", "name": "6 de Copa", "rank": 12, "position": 5},
    {"number": 7, "suit": "cups", "name": "7 de Copa", "rank": 11, "position": 6},
    {"number": 10, "suit": "cups", "name": "10 de Copa", "rank": 10, "position": 9},
    {"number": 11, "suit": "cups", "name": "11 de Copa", "rank": 9, "position": 10},
    {"number": 12, "suit": "cups", "name": "12 de Copa", "rank": 8, "position": 11},
    {
        "number": 1,
        "suit": "spades",
        "name": "Ancho de Espadas",
        "rank": 1,
        "position": 0,
    },
    {"number": 2, "suit": "spades", "name": "2 de Espada", "rank": 6, "position": 1},
    {"number": 3, "suit": "spades", "name": "3 de Espada", "rank": 5, "position": 2},
    {"number": 4, "suit": "spades", "name": "4 de Espada", "rank": 14, "position": 3},
    {"number": 5, "suit": "spades", "name": "5 de Espada", "rank": 13, "position": 4},
    {"number": 6, "suit": "spades", "name": "6 de Espada", "rank": 12, "position": 5},
    {"number": 7, "suit": "spades", "name": "7 de Espada", "rank": 3, "position": 6},
    {"number": 10, "suit": "spades", "name": "10 de Espada", "rank": 10, "position": 9},
    {"number": 11, "suit": "spades", "name": "11 de Espada", "rank": 9, "position": 10},
    {"number": 12, "suit": "spades", "name": "12 de Espada", "rank": 8, "position": 11},
]
